151 login test
espoo-dev/espoo-dev pull request #182
Opened 2021-05-21 21:06 UTC by IuryNogueira

2021-05-22 11:09 UTC, ValmirJuniorr approved these changes
LGTM.

2021-05-22 11:09 UTC, ValmirJuniorr commented on frontend/cypress/fixtures/example.json
> +}
```suggestion
}

```

2021-05-22 12:33 UTC, andersonmalheiro requested changes

2021-05-22 12:33 UTC, andersonmalheiro commented on frontend/cypress/integration/login/login.spec.js
> +  });
I think you can add an statement checking if the input has the value typed, like this:

```suggestion
  it('should show and type email', () => {
    cy.get('#email')
      .type('admin@gmail.com')
      .should('have.value', 'admin@gmail.com');
  });
```

Same thing for the other cases below

2021-05-22 12:33 UTC, andersonmalheiro commented on frontend/cypress/integration/login/login.spec.js
> +  });
You could also intercept the request to check if it returns an error
https://docs.cypress.io/api/commands/intercept#Intercepting-a-response

2021-05-28 15:57 UTC, edimossilva approved these changes
LGTM!!! 

Did you create an issue to add it to CI?

2021-05-28 20:02 UTC, IuryNogueira commented
> LGTM!!!
> 
> Did you create an issue to add it to CI?
> 
> your commits looks strange =z

this commit? https://github.com/espoo-dev/espoo-dev/pull/182/commits/13009b5c1f792fb5391590e9f927eea059c9ca2b

2021-05-31 11:11 UTC, IuryNogueira commented
this pull request too fix #209

2021-05-31 20:56 UTC, merged