Update swagger doc
espoo-dev/espoo-dev pull request #492
Opened 2022-01-14 11:57 UTC by PolinaStamenova

fix #issuenumber

# Update swagger documentation

- Add some missing properties into the schema.
- Remove extra added properties from the schema.
- Rename some descriptions into the paths.

#### Only select the appropriate.

- [ ] **Model testing.**
- [ ] **Request testing and swagger doc update.**
- [ ] **System testing.**
- [ ] **No tests required.**

2022-01-14 13:10 UTC, edimossilva requested changes
Nice, thanks for working on this.
I have some small suggestions

2022-01-14 13:10 UTC, edimossilva commented on backend/swagger/v1/swagger.yaml
> +      summary: Add a new Answers Survey to the store
This one I would return to `Create Answers Survey`.
Reasons
- The term `Add` usually is related to `array` or `list` data structures
- The term `store` usually is related to a storage pattern in front ent.

2022-01-14 13:10 UTC, edimossilva commented on backend/swagger/v1/swagger.yaml
> +      summary: List a single Answers Survey by ID
List word is associated to arrays, so I would go with `Get Answers Survey by ID` or `Retrieve Answers Survey by ID`

2022-01-14 13:10 UTC, edimossilva commented on backend/swagger/v1/swagger.yaml
> +      summary: Add a new Answer to the store
same here

2022-01-14 20:51 UTC, iurynogueira commented
Issue number pls.

2022-01-21 15:37 UTC, edimossilva approved these changes

2022-01-21 15:37 UTC, merged