Add find_or_create_not_completed_answer_survey
espoo-dev/espoo-dev pull request #524
Opened 2022-01-19 12:47 UTC by PolinaStamenova

fix #491

# Fix raising error "Should exist only one not completed by survey and user." 

- Create `find_or_create_not_completed_answer_survey`  that check if there is an existing `AnswersSurvey` (_not copleted_) and return it. In case it does NOT exist it will create a new one.

#### Only select the appropriate.

- [ ] **Model testing.**
- [ ] **Request testing and swagger doc update.**
- [ ] **System testing.**
- [ ] **No tests required.**

2022-01-19 12:52 UTC, edimossilva requested changes
Please add system tests for it

2022-01-19 15:17 UTC, edimossilva requested changes
@PolinaStamenova , my bad, I didn't notice that this won't work.
The first time the user is answering a survey it will create the first AnswersSurvey.
The second time the user is answering a survey it will create a second AnswersSurvey.

2022-01-20 07:56 UTC, edimossilva commented
> @PolinaStamenova , my bad, I didn't notice that this won't work. The first time the user is answering a survey it will create the first AnswersSurvey. The second time the user is answering a survey it will create a second AnswersSurvey.

@PolinaStamenova , my bad I didn't pay attention to `if answer_survey&.not_completed?`. Please, just add specs for it

2022-01-20 08:10 UTC, PolinaStamenova commented
> Please add system tests for it

I checked yesterday, but all test are passing. I am not sure what else can be tested?

2022-01-20 14:41 UTC, edimossilva approved these changes
Nice work, 
also good job refactoring other specs

2022-01-20 14:41 UTC, edimossilva commented on backend/spec/requests/answers_survey_request_spec.rb
> +      expect(response).to have_http_status :found
:found status is returned, but in my mind should be :created, does it make sense?

I am not familiar with this kind of test so I have no strong opinion about this

2022-01-20 14:43 UTC, merged