517 - Adding husky configuration
espoo-dev/espoo-dev pull request #528
Opened 2022-01-20 16:26 UTC by andersonmalheiro

fix #517

# Adding husky configuration

#### Only select the appropriate.

- [ ] **Model testing.**
- [ ] **Request testing and swagger doc update.**
- [ ] **System testing.**
- [x] **No tests required.**

2022-01-20 22:14 UTC, iurynogueira requested changes

2022-01-20 22:14 UTC, iurynogueira commented on frontend/.lintstagedrc.json
> +    "npm run lint --max-warnings=0",
What do you think about using yarn as default?

2022-01-21 00:07 UTC, andersonmalheiro commented
⚠️  Don't merge until #529 its merged

2022-01-21 00:30 UTC, closed without merging

2022-01-21 00:31 UTC, andersonmalheiro commented
Closing because I have made a new branch with a cleaner history