🔨  Opening survey by id in URL
espoo-dev/espoo-dev pull request #635
Opened 2022-02-20 11:37 UTC by iurynogueira

fix #599

2022-02-20 12:37 UTC, edimossilva approved these changes
LGTM

2022-02-20 13:10 UTC, andersonmalheiro requested changes

2022-02-20 13:10 UTC, andersonmalheiro commented on frontend/src/pages/surveys/[id].tsx
> +  };
I suggest wrapping this block in a try/catch/finally, and call the `setLoading(false)` inside the `finally`

2022-02-20 13:10 UTC, andersonmalheiro commented on frontend/src/pages/surveys/[id].tsx
> +  const { id } = router.query;
I suggest to add a validation on the `id` to prevent the user of type any value in the URL, like a word instead of a number and breaking the request

2022-02-23 12:35 UTC, andersonmalheiro approved these changes

2022-02-23 12:36 UTC, merged