Migrated to Navigation Component
espoo-dev/espoo-dev pull request #696
Opened 2022-03-29 14:48 UTC by amiapmorais

fix #664 

# Add Appropriate Title

## Type of changes

- [ ] **Refactor**
---

## Checklist:

- [ ] My code is understandable
- [ ] My code follows the styleguide of this project
- [ ] My changes don't generate new warnings/errors
- [ ] I have performed a self-review of my own code (build/lint/tests)
- [ ] **No tests required.**

![image](https://user-images.githubusercontent.com/72503400/160639318-14f52d9f-6d50-41d9-8a1e-9feb958debb2.png)

2022-04-03 14:05 UTC, roandersonpinheiro requested changes

2022-04-05 17:45 UTC, amiapmorais commented on android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginFragment.kt
> +            } else {
Thank you for your reviews @roandersonpinheiro. I'm not totally familiarized with the MVVM arquiteture, working with ViewModel classes. I thought I could implement the MVVM arquiteture later in the project, but maybe it's a good time to do this. I will create a specific issue to this and start to working this week.

2022-04-05 17:50 UTC, roandersonpinheiro commented on android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginFragment.kt
> +            } else {
Okay Ami, good job. If you need help I can help you with that.

2022-04-05 17:55 UTC, amiapmorais commented on android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginFragment.kt
> +            } else {
I'm very grateful. If a need it I'll ask for help, you bet. And when I done I will ask your review anyway.

2022-04-05 17:57 UTC, roandersonpinheiro commented on android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginFragment.kt
> +            } else {
Ok @amiapmorais , we can create another task to refactor the code and think of an architecture to implement, what do you think?

2022-04-05 18:29 UTC, amiapmorais commented on android-client/Espoo/app/src/main/java/com/espoo/android/view/LoginFragment.kt
> +            } else {
Let's do that.

2022-04-05 18:32 UTC, merged