✨ Add survey icon to survey in trail page
espoo-dev/espoo-dev pull request #717
Opened 2022-04-11 23:35 UTC by iurynogueira

fix #715 

# Add survey icon to survey in trail page

## Type of changes

Please delete options that are not relevant.

- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Breaking change**

---

## Checklist:

- [x] My code is understandable
- [x] My code follows the styleguide of this project
- [x] My changes don't generate new warnings/errors
- [x] I have performed a self-review of my own code (build/lint/tests)

  ### Frontend

  - Components:

    - [x] I have implemented/updated unit tests
    - [ ] I have implemented/updated Storybook documentation

  - Pages:
    - [ ] I have implemented/updated E2E tests

2022-04-12 20:21 UTC, edimossilva approved these changes
LGTM!
I've made a few suggestions about some naming conventions, definitely not blockers but I believe they bring some small improvements

2022-04-12 20:21 UTC, edimossilva commented on frontend/src/components/roadmap-survey/roadmap-survey.styles.ts
> +  background-image: url(${(props) => props.icon_url || '/assets/survey.png'});
Maybe rename this file to `default_survey_icon.png` or `survey_icon.png`

2022-04-12 20:21 UTC, edimossilva commented on frontend/src/components/roadmap-survey/roadmap-survey.test.tsx
> +  it('should render survey icon background', () => {
maybe `it should render "icon from icon_url" when the survey has  "icon_url"`

2022-04-12 20:21 UTC, edimossilva commented on frontend/src/components/roadmap-survey/roadmap-survey.test.tsx
> +  it('should render survey default icon background when dont have icon', () => {
maybe `it should render "default survey icon" when the survey has no "icon_url"`

2022-04-12 22:57 UTC, andersonmalheiro requested changes

2022-04-12 22:57 UTC, andersonmalheiro commented on frontend/src/components/roadmap-survey/roadmap-survey.styles.ts
> +export const IconItem = styled.div<{ status: StatusGroup, icon_url: string }>`
I suggest creating an interface for this

2022-04-13 23:02 UTC, iurynogueira commented
Thank you guys!

2022-04-13 23:03 UTC, mizek1 approved these changes

2022-04-14 00:49 UTC, merged