Unify docker compose
espoo-dev/espoo-dev pull request #73
Opened 2021-04-26 22:25 UTC by IuryNogueira

2021-04-27 06:20 UTC, edimossilva requested changes
link the issue (next time)
I am checking why CI is not running for your PR

2021-04-27 06:20 UTC, edimossilva commented on README.md
> +docker-compose -f docker-compose.dev.yml up
I think that is simpler if we use docker-compose.yml for dev and docker-compose.prod.yml for prod.
During daily usage have to add `-f docker-compose.dev.yml` to every command is not so coll, what do you think?

2021-04-27 06:20 UTC, edimossilva commented on README.md
> +```
Also add the urls to access the apps

2021-04-28 05:12 UTC, merged

2021-04-28 05:27 UTC, edimossilva commented
@IuryNogueira Very nice, the readme is so pretty

2021-04-28 11:07 UTC, IuryNogueira commented
> @IuryNogueira Very nice, the readme is so pretty

Thanks!