[UPDATE] notification in slack on user create
espoo-dev/espoo-dev pull request #797
Opened 2022-09-17 18:50 UTC by nikhilbhatt

fix #736 

# Add Appropriate Title

## Type of changes

Please delete options that are not relevant.

- [ ] **Bug fix**
- [ ] **New feature**
- [ ] **Breaking change**

---

## Checklist:

- [ ] My code is understandable
- [ ] My code follows the styleguide of this project
- [ ] My changes don't generate new warnings/errors
- [ ] I have performed a self-review of my own code (build/lint/tests)

  ### Backend

  Please delete options that are not relevant.

  - [ ] **Model testing.**
  - [ ] **Request testing and swagger doc update.**
  - [ ] **System testing.**
  - [ ] **No tests required.**

  ### Frontend

  - Components:

    - [ ] I have implemented/updated unit tests
    - [ ] I have implemented/updated Storybook documentation

  - Pages:
    - [ ] I have implemented/updated E2E tests

2022-09-19 13:02 UTC, danielnottingham approved these changes

2022-09-19 13:08 UTC, philipeleandro approved these changes
@nikhilbhatt You can try to specify a little bit better on PR description what you did, how we can test what you did. Just a few tips. Good job!

2022-09-19 14:48 UTC, edimossilva requested changes
Hey @nikhilbhatt, I was thinking in some approach like what is done [here](https://github.com/espoo-dev/espoo-dev/blob/main/backend/app/controllers/api/v1/answers_controller.rb#L3), the inspiration come from [this](https://www.youtube.com/watch?v=XH1fbvexqyU)

We are trying to keep the the model a bit more isolated from the business logic. One of the ways of doing this is to have business logic in the services layer. 

Sorry for not putting this in the issue description, this approach is brand new to the project.

I am also letting some comments with my some input I consider useful to provide some feedback

2022-09-19 14:48 UTC, edimossilva commented on backend/app/models/user.rb
> +  def slack_notify
If we were going with this approach I would suggest a more descriptive name like `slack_notify_after_creation`

2022-09-19 14:48 UTC, edimossilva commented on backend/app/models/user.rb
> +  def message
`message` is also a non specific name for a method like this, I rather go with something like `after_creation_message`

2022-09-19 14:48 UTC, edimossilva commented on backend/app/models/user.rb
> +      admin: Role.find_by(role_type: Role::ADMIN)&.users_count || 0,
In this case I would refactor this to scopes in the Role class. This scope would receive a role as parameter

2022-09-21 11:40 UTC, edimossilva approved these changes
Hey great work, thanks!

2022-09-21 11:41 UTC, merged